export const ALL_MOVIES = 'ALL_MOVIES';
export const FILTER_BY_TITLE = 'FILTER_BY_TITLE';
export const REQUEST_HAS_ERRORED = 'REQUEST_HAS_ERRORED';
export const REQUEST_IS_LOADING = 'REQUEST_IS_LOADING';
export const REQUEST_FETCH_DATA_SUCCESS = 'REQUEST_FETCH_DATA_SUCCESS';
export const CHANGE_LOGIN_TEXT = 'CHANGE_LOGIN_TEXT';
export const CHANGE_PASSWORD_TEXT = 'CHANGE_PASSWORD_TEXT';